# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
  TextBookCollection.create(title:'Marugoto 1', picture_url: 'http://jfstandard.jp/images/language/img_beginner_understand01.gif')
  TextBookCollection.create(title:'Marugoto 2', picture_url: 'http://jfstandard.jp/images/language/img_first_understand01_01.gif')
  TextBookCollection.create(title:'Marugoto 3', picture_url: 'http://jfstandard.jp/images/language/img_first_understand02_01.gif')
  TextBookCollection.create(title:'Marugoto 4', picture_url: 'http://jfstandard.jp/images/language/img_first_active01_03.gif')


  VocabularyDrillItem.create(native_reading: '～ついて', translated_reading: 'о　～', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: '１ばんめ', translated_reading: 'первый (по счету)', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'あかるい', translated_reading: 'светлый (в прямом и переносном смысле)', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'いみ', translated_reading: 'смысл', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'うまれました', translated_reading: 'родился', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'かいてき', translated_reading: 'удобный', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'かざっています', translated_reading: 'висит, украшает', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'かんがえています', translated_reading: 'размышляет', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'きょうだい', translated_reading: 'братья/братья и сестры', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'けんこう', translated_reading: 'здоровье/здоровый', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ごしゅじん', translated_reading: 'муж (вежливо о чьем-то муже)', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'さっか', translated_reading: 'писатель', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ざっし', translated_reading: 'журнал', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'じこしょうかい', translated_reading: 'представление, рассказ о себе', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'しぜん', translated_reading: 'природа', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'じぶんで', translated_reading: 'сам', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'しま', translated_reading: 'остров', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'しゅっしん', translated_reading: 'место, откуда вы родом', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'しょうせつ', translated_reading: 'роман', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'しんぱいします', translated_reading: 'беспокоиться', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'すんでいるところ', translated_reading: 'место проживания', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'せんしゅう', translated_reading: 'прошлая неделя', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'たいせつ', translated_reading: 'важный', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'てつだいます', translated_reading: 'помогать', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'でんしじしょ', translated_reading: 'электронный словарь', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'どくしん', translated_reading: 'холостой/не замужем', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'どろ', translated_reading: 'грязь', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ならっています', translated_reading: 'изучает', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'にがて', translated_reading: 'слабая сторона', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'はなび', translated_reading: 'фейерверк', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ピーマン', translated_reading: 'перец (болгарский)', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ひとりっこ', translated_reading: 'единственный ребенок', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ひみつ', translated_reading: 'секрет', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ほかの～', translated_reading: 'другой ～', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ほんや', translated_reading: 'книжный магазин', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'ほんやく', translated_reading: 'устный перевод', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'まじめ', translated_reading: 'серьезный, добросовестный', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'むら', translated_reading: 'деревня', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'やくそく', translated_reading: 'обещание, уговор, договоренность', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'やさしい', translated_reading: 'добрый', text_book_collection_id: TextBookCollection.all[2].id)
  VocabularyDrillItem.create(native_reading: 'りょこう', translated_reading: 'путешествие, поездка', text_book_collection_id: TextBookCollection.all[2].id)


KanjiDrillItem.create(native_reading: '１番目', translated_reading: '１ばんめ(первый (по счету))', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '意味', translated_reading: 'いみ(смысл)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '自己紹介', translated_reading: 'じこしょうかい(представление, рассказ о себе)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '自分で', translated_reading: 'じぶんで(сам)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '住んで～', translated_reading: 'すんでいるところ(место проживания)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '先週', translated_reading: 'せんしゅう(прошлая неделя)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '本屋', translated_reading: 'ほんや(книжный магазин)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '旅行', translated_reading: 'りょこう(путешествие, поездка)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '韓国料理', translated_reading: 'かんこくりょうり(корейская кухня)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '低い', translated_reading: 'ひくい(низкий)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '短い', translated_reading: 'みじかい(короткий)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '客', translated_reading: 'きゃく(гость, клиент)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '牛肉', translated_reading: 'ぎゅうにく(говядина)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '紹介', translated_reading: 'しょうかい（します）(знакомить, рекомендовать, представлять)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '地方', translated_reading: 'ちほう(местность, регион)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '冷たい', translated_reading: 'つめたい(холодный, прохладный)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '有名', translated_reading: 'ゆうめい(известный, знаменитый)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '洋食', translated_reading: 'ようしょく(европейская кухня)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '和食', translated_reading: 'わしょく(японская кухня)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '味', translated_reading: 'あじ(вкус)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '塩', translated_reading: 'しお(соль)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '全部', translated_reading: 'ぜんぶ(все, целиком)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '茶わん', translated_reading: 'ちゃわん(чайная чашка)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '生卵', translated_reading: 'なまたまご(сырое яйцо)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '～中', translated_reading: '～ちゅう(во время ～)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '運転', translated_reading: 'うんてん（します）(водить машину)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '空港', translated_reading: 'くうこう(аэропорт)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '自然', translated_reading: 'しぜん(природа)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '島', translated_reading: 'しま(остров)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '旅', translated_reading: 'たび(путешествие)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '船', translated_reading: 'ふね(лодка, корабль)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '森', translated_reading: 'もり(роща)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '予約', translated_reading: 'よやく（します）(бронировать)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '明るい', translated_reading: 'あかるい(светлый)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '泳ぎます', translated_reading: 'およぎます(плавать)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '観光地', translated_reading: 'かんこうち(достопримечательности)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '牛車', translated_reading: 'ぎゅうしゃ(повозка)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '空気', translated_reading: 'くうき(воздух)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '参加', translated_reading: 'さんか（します）(принимать участие)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '女性', translated_reading: 'じょせい(женщина)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '男性', translated_reading: 'だんせい(мужчина)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '動物', translated_reading: 'どうぶつ(животные)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '内容', translated_reading: 'ないよう(содержание)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '文化', translated_reading: 'ぶんか(культура)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '便利', translated_reading: 'べんり（な）(удобный)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '無料', translated_reading: 'むりょう(бесплатный)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '森', translated_reading: 'もり(роща)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '料金', translated_reading: 'りょうきん(плата, цена за услугу)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '集まります', translated_reading: 'あつまります(собираться)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '受付', translated_reading: 'うけつけ(ресепция, прием)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '同じ', translated_reading: 'おなじ(одинаковый)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '～電話', translated_reading: 'けいたいでんわ(сотовый телефон)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '外', translated_reading: 'そと(снаружи, на улице)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '中止します', translated_reading: 'ちゅうしします(отменять)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '広場', translated_reading: 'ひろば(площадь)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '問題', translated_reading: 'もんだい(проблема, задание)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '急ぎます', translated_reading: 'いそぎます(торопиться)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '歌', translated_reading: 'うた(песня)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '会場', translated_reading: 'かいじょう(место проведения)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '参加します', translated_reading: 'さんかします(принимать участие)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '参加者', translated_reading: 'さんかしゃ(участник)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '参加費', translated_reading: 'さんかひ(плата за участие)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '上手', translated_reading: 'じょうず(умелый)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '日時', translated_reading: 'にちじ(дата и время)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '日本祭', translated_reading: 'にほんまつり(японский фестиваль)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '入場料', translated_reading: 'にゅうじょうりょう(плата за вход)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '広場', translated_reading: 'ひろば(площадь)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '短い', translated_reading: 'みじかい(короткий)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '無料', translated_reading: 'むりょう(бесплатно)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '忙しい', translated_reading: 'いそがしい(занятой)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '～料理', translated_reading: 'おせちりょうり(праздничная (новогодняя) еда)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '親', translated_reading: 'おや(родители)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '元旦', translated_reading: 'がんたん(первый день года)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '帰国', translated_reading: 'きこく(возвращение на родину)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '今年', translated_reading: 'ことし(этот год)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '正月', translated_reading: 'しょうがつ(Новый год)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '特別', translated_reading: 'とくべつ（な）(особенный)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '年始', translated_reading: 'ねんし(начало года)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '年末', translated_reading: 'ねんまつ(конец года)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '平成', translated_reading: 'へいせい(эпоха Хэйсэй )', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '喜びます', translated_reading: 'よろこびます(радоваться, веселиться)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '意味', translated_reading: 'いみ(смысл)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '祝います', translated_reading: 'いわいます(праздновать)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '大人', translated_reading: 'おとな(взрослый)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '結婚式', translated_reading: 'けっこんしき(свадебная церемония)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '合格', translated_reading: 'ごうかく（します）(сдать (экзамен), пройти (тест))', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '参加', translated_reading: 'さんか(участие)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '幸せ', translated_reading: 'しあわせ(счастье)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '出国', translated_reading: 'しゅっこく(выезд заграницу)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '成人式', translated_reading: 'せいじんしき(торжество по случаю совершеннолетия)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '成長', translated_reading: 'せいちょう(рост)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '外', translated_reading: 'そと(снаружи, на улице)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '長生き', translated_reading: 'ながいき(долголетие)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '～試験', translated_reading: 'にゅうがくしけん(вступительный экзамен)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '願い事', translated_reading: 'ねがいごと(пожелание)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '願います', translated_reading: 'ねがいます(желать)', text_book_collection_id: TextBookCollection.all[2].id)
KanjiDrillItem.create(native_reading: '無料', translated_reading: 'むりょう(бесплатно)', text_book_collection_id: TextBookCollection.all[2].id)




